In [1]:
#import required libraries
import numpy as np
import pandas as pd


In [2]:
#Load train dataset
data=pd.read_csv('C:/Users/Abir Khan/Desktop/Dataset for the project/train/train.csv')
datatest=pd.read_csv('C:/Users/Abir Khan/Desktop/Dataset for the project/test/test.csv')
data.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [3]:
#Get details for data

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [4]:
#Remove columns with variance 0 as those columns will not impact the prediction and mostly those will have constant data
#to reduce number of cols remve those var=0 cols

data.var()[data.var()==0].index.values

array(['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290',
       'X293', 'X297', 'X330', 'X347'], dtype=object)

In [5]:
#drop 0 var columns
datafinal=data.drop(data.var()[data.var()==0].index.values, axis=1)
datafinal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 366 entries, ID to X385
dtypes: float64(1), int64(357), object(8)
memory usage: 11.8+ MB


In [6]:
#get features and labels

features=datafinal.iloc[:,2:]
label=datafinal.iloc[:,1].values

In [7]:
features.head()

X0 X1  X2 X3 X4 X5 X6 X8  X10  X12  ...  X375  X376  X377  X378  X379  \
0   k  v  at  a  d  u  j  o    0    0  ...     0     0     1     0     0   
1   k  t  av  e  d  y  l  o    0    0  ...     1     0     0     0     0   
2  az  w   n  c  d  x  j  x    0    0  ...     0     0     0     0     0   
3  az  t   n  f  d  x  l  e    0    0  ...     0     0     0     0     0   
4  az  v   n  f  d  h  d  n    0    0  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 364 columns]

In [8]:
#Get object columns from feature column for LE and OHE

features.describe(include=['object'])

X0    X1    X2    X3    X4    X5    X6    X8
count   4209  4209  4209  4209  4209  4209  4209  4209
unique    47    27    44     7     4    29    12    25
top        z    aa    as     c     d     v     g     j
freq     360   833  1659  1942  4205   231  1042   277

In [9]:
#Get only object column names

objcols=features.describe(include=['object']).columns.values
objcols

array(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype=object)

In [10]:
#Apply Label Encoder  for object columns. OHE is not use das this will create PC's instead of using direct variables

from sklearn.preprocessing import LabelEncoder
#from sklearn.preprocessing import OneHotEncoder

le=LabelEncoder()

for i in objcols:
  features[i]= le.fit_transform(features[i])

#ohe=OneHotEncoder(categorical_features=[0,1,2,3,4,5,6,8])

fea=features.values
#featureohe=fea #ohe.fit_transform(fea).toarray()

#featureohe
fea

array([[32, 23, 17, ...,  0,  0,  0],
       [32, 21, 19, ...,  0,  0,  0],
       [20, 24, 34, ...,  0,  0,  0],
       ...,
       [ 8, 23, 38, ...,  0,  0,  0],
       [ 9, 19, 25, ...,  0,  0,  0],
       [46, 19,  3, ...,  0,  0,  0]], dtype=int64)

In [11]:
#Standardize the data using StandardScaler

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
featuresstd = sc.fit_transform(fea)

In [12]:
#USe PCA for dimensionality reduction
#Use no of components as ALL column to identify correct number of componnets
from sklearn.decomposition import PCA

pca = PCA(n_components=364, svd_solver='full')
pca.fit(featuresstd,label)

PCA(copy=True, iterated_power='auto', n_components=364, random_state=None,
    svd_solver='full', tol=0.0, whiten=False)

In [13]:
#check explained variance ratio
pca.explained_variance_ratio_

array([6.89266892e-02, 5.68841213e-02, 4.53745695e-02, 3.42677135e-02,
       3.26430877e-02, 3.16266067e-02, 2.86252442e-02, 2.12375123e-02,
       1.97041337e-02, 1.78319550e-02, 1.64006646e-02, 1.56428622e-02,
       1.46274226e-02, 1.44833491e-02, 1.34828580e-02, 1.29516175e-02,
       1.24383219e-02, 1.17310333e-02, 1.12105051e-02, 1.07727793e-02,
       9.92512898e-03, 9.69449157e-03, 9.42523076e-03, 9.09867975e-03,
       8.74223908e-03, 8.43069482e-03, 7.90204943e-03, 7.63217614e-03,
       7.33541876e-03, 7.14905572e-03, 6.92957269e-03, 6.76677298e-03,
       6.52534438e-03, 6.41494089e-03, 6.22692040e-03, 5.99196153e-03,
       5.88086185e-03, 5.74693562e-03, 5.63702738e-03, 5.53409616e-03,
       5.50641149e-03, 5.40082599e-03, 5.33910600e-03, 5.24611598e-03,
       5.10194247e-03, 5.03232420e-03, 4.95885463e-03, 4.72691565e-03,
       4.64475228e-03, 4.56521484e-03, 4.39624472e-03, 4.32947533e-03,
       4.30322432e-03, 4.23762131e-03, 4.20211958e-03, 4.15473420e-03,
      

In [14]:
#Get mean of explained variance ratio to get the threshold value for varince
np.mean(pca.explained_variance_ratio_)

0.002747252747252748

In [15]:
#Check number of components which has explained variance >threshold value
pca.explained_variance_ratio_>0.002747252747252748

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [16]:
#PCA with n components 93 which has explained variance ratio >threshold

pca = PCA(n_components=93,svd_solver='full')
pca.fit(featuresstd,label)

finalFeatures = pca.transform(featuresstd)
finalFeatures.shape

(4209, 93)

In [17]:
label.shape

(4209,)

In [18]:
#Used No of splits for sample from 5 and increased to 5, 10 ,20,30 etc till 1000. Got a better generalized model at split=1000

from sklearn.model_selection import KFold
from xgboost import XGBRegressor

kfold=KFold(n_splits=1000,
           random_state=1,
           shuffle=True)
#kfold.split(finalFeatures)

i=0
for train,test in kfold.split(finalFeatures):
    i = i+1
    X_train,X_test = finalFeatures[train],finalFeatures[test]
    y_train,y_test = label[train],label[test]
    model = XGBRegressor(objective='reg:squarederror', learnning_rate=0.1)
    
    model.fit(X_train,y_train)
    
    if model.score(X_test,y_test) > 0.93: #model.score(X_train, y_train)
        print("Test Score: {}, train score: {}, for Sample Split: {}".format(model.score(X_test,y_test),model.score(X_train,y_train),i))
        

Test Score: 0.974017880163746, train score: 0.9521955868685419, for Sample Split: 1
Test Score: 0.956831098974932, train score: 0.9536994004834016, for Sample Split: 197
Test Score: 0.963151383843318, train score: 0.9546399631171532, for Sample Split: 269
Test Score: 0.9409404612525819, train score: 0.9519535825213398, for Sample Split: 322
Test Score: 0.9663734875179674, train score: 0.9541527439570472, for Sample Split: 368
Test Score: 0.9381214149049936, train score: 0.9523292344027178, for Sample Split: 401
Test Score: 0.930414491529307, train score: 0.9525544559427448, for Sample Split: 550
Test Score: 0.9483371975226297, train score: 0.951163375156542, for Sample Split: 596
Test Score: 0.943180985125625, train score: 0.9537225405151459, for Sample Split: 597
Test Score: 0.935972658000711, train score: 0.9551835316270261, for Sample Split: 616
Test Score: 0.9436953116558963, train score: 0.9534229257455195, for Sample Split: 635
Test Score: 0.9515860157822272, train score: 0.95287

In [20]:
#Test Score: 0.9802252551457228, train score: 0.9526122896011493, for Sample Split: 889
#Extract sample at value 889 with split 1000

kfold = KFold(n_splits=1000, 
              random_state=1,
              shuffle=True)
i=0
for train,test in kfold.split(finalFeatures):
    i = i+1
    if i == 889:
        X_train,X_test,y_train,y_test = finalFeatures[train],finalFeatures[test],label[train],label[test]

In [21]:
#fit into model and get scores using XGBoost regression

model = XGBRegressor(objective='reg:squarederror', learnning_rate=0.1)
    
model.fit(X_train,y_train)

#Check the quality of model
print("Training Accuracy ",model.score(X_train,y_train))
print("Testing Accuracy ",model.score(X_test,y_test))

Training Accuracy  0.9526122896011493
Testing Accuracy  0.9802252551457228


In [22]:
#Check model accuracy and error metrices

from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

#MAE - check this error metrics. 
mean_absolute_error(y_test,model.predict(X_test))

1.4400474548339837

In [23]:
#MAE is low which gives high accuracy
#Check modle accuracy based on R2
r2_score(y_test,model.predict(X_test), multioutput='variance_weighted')

0.9802252551457228

In [24]:
#R2 also gives good accuracy. 
#So accept this model
#Check MSE
mean_squared_error(y_test,model.predict(X_test))

3.1538612032245354

In [25]:
#Now read and process test data file and predict Y value

datatest.head()

ID  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  X380  \
0   1  az  v   n  f  d  t  a  w    0  ...     0     0     0     1     0     0   
1   2   t  b  ai  a  d  b  g  y    0  ...     0     0     1     0     0     0   
2   3  az  v  as  f  d  a  j  j    0  ...     0     0     0     1     0     0   
3   4  az  l   n  f  d  z  l  n    0  ...     0     0     0     1     0     0   
4   5   w  s  as  c  d  y  i  m    0  ...     1     0     0     0     0     0   

   X382  X383  X384  X385  
0     0     0     0     0  
1     0     0     0     0  
2     0     0     0     0  
3     0     0     0     0  
4     0     0     0     0  

[5 rows x 377 columns]

In [26]:
#Remove same columns as we did for tain dataset
#'X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290',
      # 'X293', 'X297', 'X330', 'X347'

datafinal=datatest.drop(['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290','X293', 'X297', 'X330', 'X347'], axis=1)
datafinal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 365 entries, ID to X385
dtypes: int64(357), object(8)
memory usage: 11.7+ MB


In [27]:
#Get feature columns

testFeatures=datafinal.iloc[:,1:]

#get object columns

objcolstest=testFeatures.describe(include=['object']).columns.values
objcolstest


array(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype=object)

In [28]:

#Apply Label Encoder  for object columns. 

from sklearn.preprocessing import LabelEncoder
#from sklearn.preprocessing import OneHotEncoder

le=LabelEncoder()

for i in objcolstest:
  testFeatures[i]= le.fit_transform(testFeatures[i])

f1=testFeatures.values


f1.ndim

2

In [29]:
#transform test data using PCA

transformFromPCA = pca.transform(f1)


labelpred=model.predict(transformFromPCA)
labelpred

array([109.37039 ,  89.3782  ,  92.38034 , ...,  93.89875 , 106.499275,
        86.42836 ], dtype=float32)

In [30]:
#Append Y predicted avlue in test data set

testdataforfile=pd.concat([datatest.iloc[:,0],pd.concat([pd.DataFrame(data=labelpred, columns=['y']),datatest.iloc[:,1:]], axis=1)],axis=1)

testdataforfile.head()

ID           y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  \
0   1  109.370392  az  v   n  f  d  t  a  w  ...     0     0     0     1   
1   2   89.378197   t  b  ai  a  d  b  g  y  ...     0     0     1     0   
2   3   92.380341  az  v  as  f  d  a  j  j  ...     0     0     0     1   
3   4   99.932404  az  l   n  f  d  z  l  n  ...     0     0     0     1   
4   5  108.738327   w  s  as  c  d  y  i  m  ...     1     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     0     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 378 columns]